import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Header from '@/components/header/default-header';
import { ThemeProvider } from '@/context/theme-context';
import './globals.css';

const inter = Poppins({
  weight: ['100', '400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
